name: commssion_calculator
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get_it: ^7.6.0        
  bloc: ^8.1.4         
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  intl: ^0.20.2
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  lottie: ^3.3.2
  go_router: ^17.1.0
  flutter_sticky_header: ^0.8.0
  either_dart: ^1.0.0
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/jsons/
    - assets/
    - assets/jpg/